-- 1. Создать и заполнить таблицы лайков и постов.
USE vk;

-- Таблица лайков
DROP TABLE IF EXISTS likes;
CREATE TABLE likes (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  target_id INT UNSIGNED NOT NULL,
  target_type_id INT UNSIGNED NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Таблица типов лайков
DROP TABLE IF EXISTS target_types;
CREATE TABLE target_types (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL UNIQUE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO target_types (name) VALUES 
  ('messages'),
  ('users'),
  ('media'),
  ('posts');

-- Заполняем лайки
INSERT INTO likes 
  SELECT 
    id, 
    FLOOR(1 + (RAND() * 100)), 
    FLOOR(1 + (RAND() * 100)),
    FLOOR(1 + (RAND() * 4)),
    CURRENT_TIMESTAMP 
  FROM messages;

-- Проверим
SELECT * FROM likes LIMIT 10;

-- Создадим таблицу постов
DROP TABLE IF EXISTS posts;
CREATE TABLE posts (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id INT UNSIGNED NOT NULL,
  community_id INT UNSIGNED,
  head VARCHAR(255),
  body TEXT NOT NULL,
  media_id INT UNSIGNED,
  is_public BOOLEAN DEFAULT TRUE,
  is_archived BOOLEAN DEFAULT FALSE,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

SELECT COUNT(id) FROM users;
SELECT COUNT(id) FROM communities;
SELECT COUNT(id) FROM media;

INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (1, 97, 19, 'ipsa', 'Nam laborum cupiditate et ab. Optio vel quod quis rerum. Delectus assumenda et quas dignissimos cumque sed quis minima. Velit nostrum aut suscipit alias voluptatem eos quia.', 41, 0, 1, '1970-09-29 04:34:16', '1973-04-25 14:40:28');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (2, 83, 10, 'recusandae', 'Velit occaecati tempore ipsa inventore animi voluptas nisi. Nostrum beatae quae eveniet quia autem neque et. Ducimus illum tempora blanditiis magnam aliquid quo voluptatem. Voluptate voluptatem cum quaerat numquam ut est veritatis.', 47, 1, 0, '1998-01-07 22:53:46', '1980-07-26 20:48:13');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (3, 11, 15, 'id', 'Atque dolorem vitae quam voluptas totam. Sit maiores ut labore molestias voluptatibus labore alias. Voluptas repellendus rem corrupti. Veritatis in magnam asperiores minus enim.', 8, 0, 1, '1978-12-21 21:49:49', '2007-10-06 20:46:12');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (4, 76, 1, 'temporibus', 'Velit non illum quis officia. Ut minima et commodi qui omnis. Officiis nesciunt qui quidem ipsum est ut. Dolorem ut temporibus soluta voluptatem odio voluptate.', 25, 1, 1, '2003-11-13 22:40:45', '1991-01-03 00:47:30');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (5, 38, 12, 'sint', 'Dolorem libero perspiciatis laboriosam. Suscipit deleniti rem quos aperiam maxime consequatur dolorem. Eum doloribus voluptatem excepturi. Dignissimos reprehenderit rerum cum minus.', 12, 0, 1, '1997-09-21 11:02:11', '2002-08-22 18:29:26');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (6, 38, 20, 'recusandae', 'Voluptatem animi est est praesentium officia qui facere ipsam. Et blanditiis rerum rem nihil cum fugit iste tempore. Qui cumque quia asperiores laboriosam molestiae.', 15, 1, 0, '2012-05-23 09:46:36', '1990-05-30 00:00:28');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (7, 47, 2, 'rem', 'Impedit maiores qui impedit aut dolor commodi. Est maiores alias modi temporibus nihil. Totam maiores voluptas aut aperiam cum perferendis commodi.', 26, 0, 0, '1980-06-17 20:02:45', '2014-08-13 23:31:49');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (8, 51, 8, 'sequi', 'Modi sint distinctio autem quod quasi tenetur. Voluptatibus maiores vel consequuntur consequatur aut. Tempore sed nihil magni similique minima vel.', 10, 0, 1, '1997-11-13 16:21:32', '1979-04-09 11:32:25');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (9, 73, 16, 'ut', 'Molestiae corporis explicabo recusandae sapiente maiores expedita ipsam est. Reprehenderit reiciendis odit provident pariatur. Repellat veniam nisi ut possimus.', 91, 0, 1, '1996-01-09 17:31:16', '1976-11-02 02:46:03');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (10, 63, 20, 'culpa', 'Provident aut qui culpa quia voluptatibus expedita. Et quae praesentium et nemo est suscipit. Impedit consequatur quaerat exercitationem soluta. Ex dolorum vero ut similique id occaecati.', 85, 1, 0, '1998-06-17 09:29:33', '1982-10-15 17:25:15');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (11, 73, 12, 'minima', 'Tenetur praesentium temporibus magni eius impedit exercitationem. Ea dolores autem ea id dolores eligendi. Enim aut omnis ut nihil vero reprehenderit consequatur. Cum rerum animi aut. Sunt rem et sed.', 29, 0, 0, '1972-12-14 11:34:31', '2020-10-15 22:35:24');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (12, 24, 5, 'eveniet', 'Debitis aperiam ratione tenetur. Nobis quis numquam laborum voluptatibus optio et. Earum amet ipsam est enim. Velit et iste et molestiae voluptatibus.', 69, 0, 1, '1976-07-06 22:38:55', '2001-01-31 03:33:01');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (13, 90, 18, 'veniam', 'Totam velit voluptatem quam officia perspiciatis. Non sed consectetur accusantium numquam. Quia quibusdam harum nam sunt.', 64, 1, 1, '1974-02-10 15:10:18', '1989-05-26 21:06:40');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (14, 26, 9, 'alias', 'Cupiditate placeat delectus deserunt aliquam soluta id. Unde error id maxime eos. Sint est et rerum sunt. Harum qui nemo ab.', 87, 0, 1, '2002-09-24 18:57:18', '2017-01-26 11:14:56');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (15, 34, 2, 'at', 'Sit est velit sed enim et et et. Totam distinctio aperiam dolor natus ea voluptatem. Cupiditate autem quia voluptatum saepe deleniti. Quo sequi consequatur delectus et.', 12, 0, 0, '1997-02-26 11:24:35', '1976-04-26 17:03:29');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (16, 11, 1, 'quasi', 'Sapiente perspiciatis veritatis dolores atque et corrupti impedit maiores. Nobis cum nostrum omnis optio. Rem architecto quibusdam in necessitatibus.', 97, 1, 1, '1972-07-05 00:50:49', '1987-06-30 05:26:54');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (17, 59, 8, 'occaecati', 'Sed eum iusto voluptate est fuga dolorum. Sit quia quas reprehenderit harum.', 37, 1, 0, '2002-09-21 21:29:07', '2008-03-24 10:59:31');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (18, 77, 20, 'voluptatem', 'At qui non perferendis. Sequi fuga est officia accusamus voluptatum quis. Perferendis enim quaerat quia dignissimos est vitae. Consequuntur maxime animi modi repudiandae accusamus rem.', 47, 0, 0, '1994-10-13 01:14:20', '2010-03-16 09:51:13');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (19, 37, 17, 'et', 'Laborum et assumenda consequuntur doloremque. Enim debitis autem error. Velit odio minima natus beatae id in.', 24, 1, 0, '1984-01-15 09:38:34', '1993-01-27 22:21:18');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (20, 73, 14, 'deserunt', 'Inventore quod dolorem eveniet omnis exercitationem consectetur laboriosam. Soluta fuga recusandae cum sequi pariatur.', 1, 1, 0, '2014-10-29 06:33:58', '1982-08-18 05:57:41');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (21, 2, 10, 'voluptatem', 'Facilis numquam dolor ipsam impedit molestiae sit natus. Porro est rerum eaque optio id. Mollitia ut excepturi aut sequi aut esse enim.', 74, 1, 0, '1972-06-30 14:42:33', '2003-02-15 01:13:23');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (22, 87, 15, 'qui', 'Nostrum vero aut reprehenderit eum. Nemo laborum est ut ut est facilis et quod. Quidem eius sed unde voluptates.', 44, 1, 0, '2001-08-04 21:04:59', '1972-09-10 23:41:46');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (23, 50, 8, 'qui', 'Modi quisquam consequuntur officia quis praesentium ad numquam. Labore corporis corrupti est. Vitae ut aperiam aut molestiae fugiat.', 99, 0, 0, '1983-10-07 23:13:34', '1984-04-16 19:19:32');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (24, 49, 9, 'non', 'Rerum quo laboriosam distinctio nobis. Non tempora officiis voluptas molestias pariatur explicabo. Qui animi ad rem a quibusdam. Laboriosam a et provident fugit.', 7, 1, 0, '1971-11-30 08:30:57', '1971-07-02 15:01:05');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (25, 80, 2, 'dolorem', 'Inventore voluptatem fugiat dignissimos vel aliquam corrupti. Omnis nobis nam perferendis. Ut non omnis sint voluptate quisquam. Molestiae et est aperiam architecto. Similique ducimus excepturi earum cum.', 99, 1, 1, '1975-09-29 01:31:49', '1990-12-13 04:20:04');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (26, 8, 14, 'ea', 'Ipsa a sit libero quis deserunt nam. Ut numquam ipsum eos ipsum repudiandae non. Illo dolor nihil ipsam architecto non saepe eos magnam.', 91, 0, 1, '2004-01-09 15:17:29', '1981-07-16 22:09:49');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (27, 4, 3, 'harum', 'Quasi corporis commodi molestiae dignissimos asperiores quo voluptatibus. Cumque deserunt sit cumque assumenda velit. Voluptatibus quibusdam fuga dolores autem facilis.', 2, 1, 0, '1990-05-17 01:14:17', '1991-01-26 11:17:58');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (28, 67, 16, 'minus', 'Velit illo ut est vitae sed eum. Aut ab quo sed consequatur. Dolor doloremque qui fuga veritatis. Quisquam temporibus dicta autem aut et.', 59, 1, 1, '2005-02-06 14:16:45', '2013-07-24 21:59:28');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (29, 27, 8, 'voluptatem', 'Fugit voluptates voluptatibus laborum fugiat accusantium molestias veniam. Error nihil minima natus eligendi recusandae est accusantium. Totam quos pariatur exercitationem a labore voluptas earum voluptatem. Sint eius eos et hic libero beatae.', 1, 0, 1, '1981-07-01 11:00:52', '1986-09-14 02:32:54');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (30, 62, 11, 'odio', 'Ipsum aut est quos qui. Nam excepturi qui velit tempora et. Enim illum eius commodi saepe officiis.', 87, 1, 1, '1988-06-15 23:30:14', '2018-08-21 17:17:36');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (31, 37, 19, 'nostrum', 'In blanditiis similique sit. Natus mollitia qui eius vel veritatis nisi possimus. Sed cupiditate expedita omnis voluptas et ipsam maiores.', 49, 0, 0, '1983-06-29 01:16:21', '2002-05-29 10:17:18');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (32, 60, 9, 'ipsa', 'Quasi iste porro qui in quia cum repellat. Et delectus esse sunt beatae doloribus tempora in. Omnis cupiditate repellendus voluptatem non occaecati. Aut pariatur perspiciatis est officia excepturi aperiam esse.', 100, 0, 0, '1983-11-28 19:01:35', '1977-12-11 09:12:12');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (33, 38, 6, 'iusto', 'Nihil necessitatibus molestias aliquid omnis quis voluptate officiis quis. Sit deleniti aperiam dicta placeat voluptatibus aut est.', 34, 1, 1, '1980-11-29 19:33:20', '2018-11-06 06:32:04');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (34, 90, 16, 'blanditiis', 'Sed asperiores quam aliquam. Facere accusantium sunt est illo sed architecto. Perspiciatis odio totam ut repudiandae nesciunt ut voluptas.', 12, 1, 1, '2010-04-25 05:35:04', '2009-12-04 19:21:21');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (35, 98, 18, 'suscipit', 'Nostrum unde aut est. Veniam rerum blanditiis vero voluptatibus deleniti.', 93, 1, 1, '2000-07-20 19:08:35', '2003-08-16 04:14:54');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (36, 29, 18, 'est', 'Mollitia blanditiis eius nulla. Id molestias ipsam architecto. Numquam dicta ipsa qui eaque aut velit. Nostrum minima vel fugiat facilis doloribus vitae dolores.', 95, 1, 1, '1988-05-08 19:44:28', '2019-08-19 13:58:30');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (37, 47, 20, 'possimus', 'Officia impedit fugiat eaque impedit excepturi. Rerum consequatur reiciendis maiores adipisci rerum provident excepturi. Tempore cum aut in. Incidunt modi sit quos veritatis temporibus ipsam.', 23, 1, 1, '1980-03-13 09:18:25', '1982-07-10 20:34:36');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (38, 96, 15, 'autem', 'Exercitationem cumque nobis excepturi architecto ut sit. Iste rerum nobis nihil. Sunt ut voluptatibus officiis ipsa enim cumque odio. Qui nam autem porro quos delectus non.', 91, 1, 1, '1982-03-13 16:27:34', '1990-07-03 19:59:39');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (39, 26, 2, 'sint', 'Magni repellendus rerum blanditiis eos. Quidem consequuntur quod omnis ducimus. Laboriosam ad quaerat ut reiciendis ad quibusdam facilis. Numquam atque dolorem dicta tempore.', 70, 1, 0, '2011-05-27 11:00:01', '2009-01-25 17:20:11');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (40, 29, 19, 'odio', 'Facere in ipsam sint sed. Id deleniti nisi explicabo voluptatem tempora. Aut eum recusandae in asperiores recusandae omnis. Similique quasi qui repellat totam sunt.', 95, 0, 1, '1989-12-10 03:24:28', '1976-11-02 08:20:28');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (41, 27, 1, 'quis', 'Culpa quae ea vitae. Facere quas dolores dolores nulla eum et. Rerum quibusdam consequatur qui quidem. Voluptas nobis enim non amet.', 91, 0, 1, '2000-02-22 14:29:50', '1982-03-26 09:47:44');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (42, 24, 1, 'in', 'Nobis vero ut quo expedita magnam. Voluptas itaque ipsa et voluptas voluptas.', 88, 0, 0, '2020-05-12 06:44:54', '2000-08-11 10:20:49');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (43, 7, 18, 'est', 'Vel iure voluptatum voluptates. Aut aspernatur omnis amet eveniet. Aut aliquam harum placeat dicta nostrum cum.', 15, 1, 1, '1970-12-27 19:10:02', '1999-05-09 21:34:53');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (44, 45, 6, 'nostrum', 'Porro vel eos laborum cum modi in. Qui in voluptatem nemo totam omnis. Asperiores ut expedita tenetur harum odio nostrum voluptas. Ut in fugit voluptatem beatae praesentium omnis voluptatibus.', 98, 0, 0, '1986-07-20 17:20:41', '1995-07-23 04:59:03');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (45, 61, 19, 'pariatur', 'Autem mollitia ut ut voluptatem quia. Eius nostrum corrupti doloremque vel eveniet voluptatem dignissimos laudantium. Rerum qui at earum distinctio. Placeat sint quia voluptatem optio ea. Consequatur eos eos totam facilis.', 35, 1, 0, '1988-04-17 01:17:04', '1972-10-29 16:11:19');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (46, 96, 18, 'veritatis', 'Fugiat dolorum ea et ad. Molestiae fuga voluptatem quis sunt omnis consequatur omnis hic. Cumque eius quae facilis totam praesentium est. Qui possimus eligendi quae quis alias temporibus quia.', 12, 0, 0, '2003-06-05 16:56:27', '2000-04-21 19:29:29');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (47, 21, 14, 'cumque', 'Repellendus dolore necessitatibus voluptatem fugit accusantium et. Voluptatum soluta quas quas cumque earum tempore officia esse. Sit sapiente illum soluta aut.', 16, 1, 0, '1974-08-10 17:22:48', '1971-02-06 09:37:44');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (48, 33, 1, 'et', 'Natus ea ad blanditiis distinctio. Omnis facilis voluptas impedit facere quis. Facere non unde et omnis. Sapiente maiores ab quia.', 62, 1, 0, '2015-04-04 22:28:07', '2010-12-02 05:18:51');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (49, 80, 9, 'laborum', 'Veniam qui distinctio fugit voluptas hic quis voluptatem. Ea odio nostrum quis quam. Error omnis eligendi dignissimos. At pariatur voluptas possimus vero consectetur molestiae.', 21, 0, 1, '1983-10-20 01:01:58', '2013-06-21 23:14:42');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (50, 23, 14, 'illo', 'Quos consequatur sit tempora. Nulla expedita et perspiciatis qui veritatis ea. Earum reprehenderit itaque autem aliquam quisquam quo corporis.', 2, 0, 0, '1977-11-30 15:28:15', '1972-12-12 01:23:06');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (51, 18, 13, 'beatae', 'Omnis et exercitationem est blanditiis facilis voluptas. Quam libero alias dolores ut. Fugit fuga iure fuga sint architecto.', 55, 0, 0, '2005-01-06 21:26:34', '1983-08-20 17:44:36');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (52, 7, 12, 'non', 'Consectetur atque error ut unde magni doloremque. Voluptatum sequi itaque doloremque saepe explicabo placeat non quo. Ipsa beatae voluptas et. Perferendis dolor molestiae eligendi totam corrupti est dolorum.', 7, 1, 0, '1974-05-25 03:07:43', '1974-01-06 08:15:31');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (53, 16, 20, 'officia', 'Ducimus recusandae nostrum non occaecati. Enim illum eos dolores maiores fuga qui. Ea ab saepe ea sed aspernatur magni et.', 75, 1, 1, '1996-01-09 06:20:48', '2019-12-18 03:50:05');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (54, 73, 7, 'non', 'Perspiciatis explicabo amet iste nemo. Expedita voluptas asperiores sint itaque eum non. Omnis sed et perferendis perspiciatis cupiditate iusto inventore.', 43, 0, 0, '2005-06-24 08:59:11', '2016-05-11 05:23:04');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (55, 51, 19, 'unde', 'Alias ut temporibus magnam placeat. Mollitia maiores qui tempore doloremque aspernatur sed. Voluptate voluptates repudiandae sunt dignissimos fugit rerum. Error facilis facere minus odio sed reprehenderit quaerat.', 56, 1, 1, '1989-01-02 15:05:54', '2018-03-30 09:27:19');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (56, 63, 10, 'quasi', 'Eum nesciunt autem eius. Deserunt odio ea odit repellat blanditiis iure. Voluptatem iure qui quis non magni voluptas et repudiandae. A eum ea quod in. Placeat quia quod explicabo sint ducimus et sed velit.', 49, 1, 1, '1972-03-16 06:56:00', '1980-05-07 01:18:57');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (57, 24, 5, 'non', 'Corporis debitis expedita quam dolores. Quia eos aut et omnis. Veritatis est dolor esse sint illum ullam. Illo consequuntur non doloribus praesentium harum.', 43, 0, 1, '1989-12-28 23:23:50', '1987-12-23 23:51:41');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (58, 57, 16, 'reprehenderit', 'Esse provident omnis sit. Aut sunt laborum molestias reprehenderit aut quia. Eos qui non ea non unde libero assumenda. Nemo cum similique necessitatibus.', 55, 1, 0, '1992-12-23 21:37:42', '1980-08-04 06:55:08');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (59, 82, 8, 'tenetur', 'Consequatur saepe dolorem deserunt et voluptatum. Doloribus omnis facere sed sed id maxime iusto. Sed aspernatur iure similique commodi.', 29, 0, 0, '2002-11-03 22:27:56', '2013-11-13 11:26:18');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (60, 17, 19, 'pariatur', 'Dolorem et assumenda quas consequatur alias. Hic asperiores voluptatem aut molestias et inventore.', 89, 0, 0, '1988-09-21 17:14:06', '1985-04-23 15:23:51');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (61, 49, 5, 'est', 'Accusantium qui omnis enim dolorem iure. Velit nobis neque natus quia voluptatem deserunt. Odit officiis omnis earum laudantium autem.', 0, 1, 1, '2014-11-06 00:24:51', '2018-11-12 14:48:55');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (62, 77, 11, 'dolore', 'Reprehenderit temporibus tempora fugit. Molestiae inventore in velit nulla minus consectetur quis. Nostrum et sint accusamus blanditiis blanditiis ab. Enim ratione at dolor temporibus voluptatem asperiores voluptates.', 90, 0, 0, '1972-03-20 22:57:26', '1986-11-28 21:05:24');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (63, 22, 2, 'et', 'Dolor aperiam laborum sed culpa expedita quis voluptas. Odio totam rerum minus consequatur consequatur qui.', 29, 1, 1, '2014-12-03 13:21:41', '1977-03-15 02:35:11');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (64, 2, 7, 'ut', 'Natus iste distinctio architecto illum dolorem eum velit. Reiciendis est molestiae voluptatem rerum nisi eos et. Incidunt aspernatur corrupti vel dolor veniam. Asperiores quos excepturi voluptate animi quo harum.', 19, 1, 0, '1975-05-18 01:45:07', '1980-10-04 13:38:00');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (65, 74, 4, 'perferendis', 'Totam et aut at soluta animi debitis minus. Explicabo ab nihil quo et. Ut ut et ducimus quia provident officia voluptas provident.', 74, 0, 1, '2012-06-10 04:12:38', '1988-10-24 11:36:12');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (66, 74, 1, 'est', 'Repudiandae consequuntur minus et ut et. Et et qui ipsa ut ex odit. Officia ut adipisci ea praesentium eligendi.', 29, 1, 1, '1993-05-02 17:33:32', '1992-10-04 13:43:46');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (67, 21, 11, 'iusto', 'Esse necessitatibus sit dignissimos perspiciatis aut vitae quo. Ea rerum autem ut.', 62, 1, 0, '2013-09-27 19:40:49', '1979-04-30 21:23:41');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (68, 17, 3, 'ipsa', 'Ut amet ex vitae et quasi et incidunt earum. Iste ducimus recusandae blanditiis adipisci et.', 84, 1, 1, '2020-05-05 09:28:46', '1984-02-17 02:26:15');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (69, 26, 11, 'provident', 'Cupiditate dolor repellat vitae molestiae sint qui. Similique ut qui similique atque consectetur et rerum. Tempora ea iste quo dolore omnis. Natus illo sed quibusdam.', 77, 0, 0, '1971-08-28 21:34:26', '2015-06-07 12:33:51');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (70, 57, 14, 'ut', 'Provident voluptatem perspiciatis quisquam voluptatem vitae eveniet omnis. Rem qui id quia id suscipit. Aut asperiores qui tenetur natus ullam ut soluta. Sunt et ullam nesciunt reprehenderit distinctio molestiae. Unde fugiat modi sapiente rem perferendis adipisci rerum sint.', 29, 1, 0, '1991-06-24 10:55:28', '2013-01-30 04:18:33');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (71, 64, 14, 'non', 'Quia corporis ad aut aut laudantium. Cumque eligendi explicabo atque voluptates rem. Repellendus vel vitae quo omnis. Alias sint ut facilis.', 38, 0, 1, '2002-09-24 04:17:09', '1999-04-19 16:43:25');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (72, 39, 13, 'aliquid', 'Laborum qui quia quidem ipsam aut iste molestias. Laudantium maiores tempore culpa voluptatem quia quaerat et. Culpa rerum consectetur repellendus mollitia. Facilis autem cumque sed officiis error in aut.', 10, 1, 0, '1992-12-12 16:17:21', '2013-12-02 02:28:25');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (73, 38, 20, 'in', 'Qui qui fugiat enim asperiores id adipisci. Sit et minima ipsam culpa est. Est consectetur qui veniam quia. Reprehenderit nam laborum eveniet quidem possimus et blanditiis.', 51, 1, 0, '1995-08-29 13:06:34', '1971-10-20 09:25:56');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (74, 17, 20, 'ullam', 'Ratione fugiat error qui dolorem et ad enim. Optio et deserunt repudiandae. Voluptatem ut itaque unde quod eum nulla sunt dolorem.', 46, 0, 0, '1990-02-28 06:23:20', '1971-07-19 17:46:34');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (75, 55, 20, 'dolorum', 'Voluptas et minus sapiente voluptas cupiditate iure. Ipsam ut et dolores ab facilis rerum minus.', 20, 0, 0, '1976-12-27 21:14:08', '2010-04-10 07:54:38');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (76, 61, 12, 'repudiandae', 'Voluptatum beatae est consequatur sunt aut. Qui qui molestiae nesciunt ut. Est quisquam a deleniti earum voluptatem vel.', 30, 1, 1, '1983-10-11 05:54:28', '2017-11-27 19:10:39');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (77, 22, 8, 'officiis', 'Quia enim sed rerum assumenda animi perferendis. Similique saepe est laudantium et odit impedit. Debitis qui ab est quod quaerat.', 58, 0, 0, '1984-06-08 15:26:52', '1986-07-15 20:27:35');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (78, 63, 9, 'ut', 'Voluptates sit quo voluptas velit officia. Dignissimos magnam animi a. Non provident possimus atque repellendus non ut saepe aut.', 44, 0, 0, '1999-04-12 20:58:12', '2019-11-23 22:29:14');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (79, 1, 5, 'inventore', 'Doloremque est ratione delectus ducimus iusto autem. Atque sequi incidunt eaque nemo. Odit velit perspiciatis voluptas laudantium. Accusantium nihil dignissimos voluptas laborum et sint vel nam.', 48, 1, 0, '1994-05-03 15:18:56', '2017-03-18 12:06:57');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (80, 26, 20, 'porro', 'Beatae excepturi incidunt ut voluptas distinctio. Hic aspernatur blanditiis dignissimos commodi autem. Enim occaecati sed qui vitae ab sequi doloribus.', 48, 1, 0, '1980-05-01 10:09:12', '1998-04-24 23:10:35');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (81, 81, 19, 'et', 'Debitis enim quod rerum iusto. Quod eaque qui quos laboriosam eveniet ea. Aliquid et quibusdam quos veritatis libero. Dolorum eum minus eligendi tempora provident facilis labore.', 35, 0, 1, '1999-10-31 00:16:11', '1991-07-23 23:09:47');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (82, 29, 1, 'non', 'Maxime maxime iure atque. Ut blanditiis commodi enim hic ut vero ut. Et aut ut eos incidunt eaque sunt.', 70, 0, 0, '2011-10-16 15:21:47', '2010-01-04 02:31:47');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (83, 92, 17, 'culpa', 'Beatae cum voluptatem illum. Reprehenderit tenetur repellat deserunt et tenetur.', 87, 1, 1, '1977-02-26 05:05:24', '1990-01-25 21:13:28');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (84, 92, 17, 'saepe', 'Accusantium sequi provident asperiores quia consequatur quidem repudiandae. Iusto et eos rerum assumenda mollitia. Qui aliquam velit omnis expedita error.', 69, 0, 0, '1981-01-08 14:42:07', '1978-03-10 23:37:37');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (85, 96, 17, 'dignissimos', 'Ullam nulla temporibus cumque sit maxime aut blanditiis. Occaecati expedita est praesentium. Consequatur explicabo eum nulla. Similique quisquam porro at reiciendis.', 70, 1, 1, '1985-10-21 23:56:58', '2009-09-07 05:36:32');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (86, 60, 3, 'voluptatem', 'Sint tempore numquam dolores doloremque soluta. In sapiente reiciendis maxime praesentium est possimus. Repellendus ullam et ut accusantium enim amet.', 6, 1, 1, '1983-03-14 10:07:34', '1994-02-16 06:25:43');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (87, 86, 11, 'tempore', 'Dolorem tenetur voluptates et. Repellat eos tempore qui tenetur quia eos autem. Impedit ex odit recusandae dolor.', 98, 1, 0, '2019-08-04 16:14:34', '2006-02-17 08:15:09');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (88, 65, 8, 'magnam', 'Aliquid odit recusandae quisquam id. Non eius qui animi quae. Dignissimos id qui ut vel eligendi deserunt. Ex perferendis aut voluptates animi veniam molestiae.', 80, 0, 1, '2007-11-27 07:48:19', '1996-11-11 03:57:32');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (89, 74, 14, 'aperiam', 'Aut accusantium incidunt quasi sint. Ut repudiandae quasi soluta ut aut tenetur adipisci. Ea accusantium et laudantium quaerat rerum quia ut. Dolores veniam excepturi et quia rerum inventore ipsam aut.', 70, 0, 0, '2005-02-27 00:10:12', '1974-06-21 17:16:26');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (90, 37, 10, 'sed', 'Repudiandae ratione hic nulla consequatur fugiat quibusdam optio. Dolores qui veniam recusandae facere non. Dolorem aut corporis eos neque earum sunt.', 96, 0, 1, '2007-03-26 10:26:22', '2008-11-19 13:56:16');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (91, 34, 17, 'sint', 'Vero hic quia vel harum in explicabo. Et iste quibusdam voluptatem dicta. Ullam cumque non magnam. Voluptate sit et voluptas temporibus consectetur ab possimus.', 40, 0, 1, '1990-06-15 04:24:48', '2017-07-11 13:30:19');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (92, 51, 7, 'placeat', 'Molestiae voluptas illum cum. Ex consequatur ut distinctio dolorem enim odio architecto. Quis non est rerum autem consectetur architecto aut. Praesentium doloribus numquam ipsam repellendus dolorum atque doloribus dolorem. Commodi ipsa eos nobis corporis.', 70, 1, 0, '1995-02-09 17:46:20', '1982-02-26 07:16:42');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (93, 63, 1, 'et', 'Vel eligendi facere quidem libero. Explicabo beatae inventore deserunt dolore. Sed enim iusto sint ut consequatur.', 28, 1, 0, '1974-11-30 06:08:32', '1999-07-18 16:24:23');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (94, 53, 18, 'ullam', 'Ut aliquid quia quis occaecati facilis sapiente rerum. Nobis hic perferendis et quisquam. Id ducimus et dolorem iure a. Eius recusandae officia a. Quaerat eveniet quo voluptatibus maxime consequatur.', 80, 1, 0, '2008-02-12 06:46:16', '2017-11-08 09:01:26');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (95, 75, 20, 'aliquam', 'In officia magni et distinctio asperiores quibusdam. Recusandae excepturi quia accusamus dolore quas omnis et. Quos nam voluptas ut temporibus odit debitis tempora. Quasi eum deleniti unde iusto nobis.', 98, 1, 0, '2003-11-24 05:55:37', '2017-12-03 21:27:31');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (96, 65, 17, 'aliquam', 'Laborum veniam qui deleniti ipsa praesentium. Omnis qui assumenda illo. Sunt laudantium nisi tempore nam.', 72, 0, 0, '1974-09-19 13:41:48', '2003-08-25 10:12:26');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (97, 68, 20, 'maiores', 'Molestiae consequatur asperiores animi ut autem doloremque. Ipsa nostrum ut illum et. Dolores deleniti saepe tempora perspiciatis incidunt est.', 57, 1, 1, '1979-03-01 23:08:17', '2006-10-27 03:23:15');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (98, 70, 18, 'et', 'Veritatis repudiandae consequatur aliquid iusto repudiandae pariatur in. Ullam voluptatem ducimus cupiditate vel aperiam voluptatibus. Ut perferendis quis enim omnis culpa maxime. Dolores et quisquam assumenda dolorum nisi est neque. Magnam non ad minus.', 66, 1, 0, '1988-05-05 10:24:04', '2016-01-09 06:12:04');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (99, 29, 12, 'ex', 'Dolor dolores velit voluptatem beatae sint molestias esse. Quibusdam inventore nostrum sit.', 23, 0, 1, '1996-12-04 23:59:54', '1987-09-28 14:16:53');
INSERT INTO `posts` (`id`, `user_id`, `community_id`, `head`, `body`, `media_id`, `is_public`, `is_archived`, `created_at`, `updated_at`) VALUES (100, 36, 3, 'dolor', 'Nulla enim omnis est tempore. Est blanditiis dolorum deserunt rerum. Voluptatem non beatae quae natus accusantium et voluptate.', 75, 1, 1, '2020-05-24 10:10:16', '2003-02-14 22:56:36');

UPDATE posts 
SET updated_at = NOW()
WHERE updated_at < created_at;

SELECT * FROM posts LIMIT 10;

DROP TABLE IF EXISTS media_likes;
DROP TABLE IF EXISTS posts_communities;
DROP TABLE IF EXISTS posts_communities_media;
DROP TABLE IF EXISTS posts_community_likes;
DROP TABLE IF EXISTS posts_users;
DROP TABLE IF EXISTS posts_users_likes;
DROP TABLE IF EXISTS posts_users_media;



